packages:
  - "."
allowBuilds:
  esbuild: true
  sharp: true

autoInstallPeers: false

minimumReleaseAgeExclude:
  - '@elog/cli@1.0.0-beta.2 || 1.0.0-beta.3 || 1.0.0-beta.4'
  - '@elog/plugin-from-notion@1.0.0-beta.2 || 1.0.0-beta.3 || 1.0.0-beta.4'
  - '@elog/plugin-to-local@1.0.0-beta.2 || 1.0.0-beta.3 || 1.0.0-beta.4'
  - '@elog/plugin-transform-image-r2@1.0.0-beta.2 || 1.0.0-beta.3 || 1.0.0-beta.4'
  - '@elog/shared@1.0.0-beta.2 || 1.0.0-beta.3'
  - '@elog/core@1.0.0-beta.1'
  - '@elog/plugin-sdk@1.0.0-beta.1'
